### ISSUE TITLE
Company_, Department_ and the likes (with underscore) not found...

### ISSUE THREAD

**Issue by divStar** [adamzareba/company-structure-spring-security-oauth2-authorities#1]
Hello,

first off: thank you for this example. I am trying / struggling to understand how to work with OAuth2, ResourceServer etc. and found your post about it on DZone (https://dzone.com/articles/secure-spring-rest-with-spring-security-and-oauth2).

After reading through it, I decided to try out the example you offered here on GitHub, but I am having a problem.

I cloned and imported the project into Eclipse, but **while it does build via _maven_** (which is odd), it **keeps showing errors in _Eclipse_**, namely, that it cannot find **Company_**, **Department_** and **Employee_**. I have no clue as to why.

I thought the classes with underscore were a feature of Lombok or something, but all of the missing classes mentioned above are imported in **CompanyRepositoryImpl** and used for static access - so I guess that there once were classes like that?
I suppose it's not a big deal to fix that (apparently it is a static list or array containing some example objects from the SQL-files?); then again perhaps they are ought to be already there and I am just doing something wrong?

Do you know what else I might have to do?

**Comment by adamzareba** [comment]
Hi,

Thanks for your feedback. It seems you have issue with annotations processing in eclipse. You have to turn on annotation processing like described in following article (section eclipse):
https://docs.jboss.org/hibernate/orm/5.0/topical/html/metamodelgen/MetamodelGenerator.html

Please, remember to install lombok plugin later on to process Lombok annotations.

After that, restart your IDE and rebuild the project.

Thanks,
Adam

**Comment by divStar** [comment]
Hi,

thank you for your reply. I didn't know I had to turn on Annotation Processing (especially since I could not find it in the usual preferences, but only in the project specific settings).
Once I found the settings (inside the project specific properties dialog), I just turned them on and added the `hibernate-jpamodelgen-5.2.12.FINAL.jar` to the Factory Path.

Then I rebuilt the whole thing and apparently it generated the missing classes.

I already had Lombok installed and working. It's just worth noting, that the classes with an underscore are not Lombok-related, but related to the JPA static metamodel generator.

Thank you for your help!

**Comment by helderhernandez** [comment]
Greetings colleagues, thank you very much for sharing the project.
I wanted to ask for your help, I have followed the [following steps](https://javabeat.net/jpa-2-metamodel-eclipse/), but the project still cannot generate the metamodels, am I missing any other configuration?
Note: I am using Eclipse Version: 2020-12 (4.18.0)
