### ISSUE TITLE
Wont boot up

### ISSUE THREAD

**Issue by IvoryAguado** [adamzareba/company-structure-spring-security-oauth2-authorities#8]
Error:java: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

**Comment by adamzareba** [comment]
What Java version are you using?

**Comment by alterGauner** [comment]
This is a Java10 issue... here you can find the solution: [https://stackoverflow.com/questions/50818901/runtimebuiltinleafinfoimpl-cannot-be-found-but-its-jar-is-added-to-pom-xml/50916881#50916881](url)

**Comment by adamzareba** [comment]
@alterGauner thanks for information. I will close this issue. 
@IvoryAguado let me know if this solution is not enough.
